// Bounded icon registry (REVAMP Phase 4.1).
// Configs reference icons by string name; importing * as lucide-react pulled
// the entire icon library (~600KB) into the bundle. Only what's listed here
// ships. Unknown names render nothing, same as the old dynamic lookup.
import {
  Anchor,
  Armchair,
  Bed,
  BedDouble,
  BookMarked,
  Box,
  Camera,
  Circle,
  Clock,
  Container,
  Disc,
  DoorOpen,
  FileText,
  Flag,
  Flashlight,
  Frame,
  GitBranch,
  Grid3x3,
  Lamp,
  Laptop,
  Lightbulb,
  Minus,
  MonitorSpeaker,
  Move,
  Package,
  Palette,
  PenTool,
  RectangleHorizontal,
  RectangleVertical,
  Search,
  ShoppingCart,
  Sofa,
  Square,
  SquareDashedBottom,
  Sun,
  Table,
  Trees,
  Tv,
  Umbrella,
  User,
  Video,
  X,
  Zap,
  ChevronDown,
  ChevronRight,
  type LucideIcon,
} from 'lucide-react';

export const ICON_MAP: Record<string, LucideIcon> = {
  Anchor,
  Armchair,
  Bed,
  BedDouble,
  BookMarked,
  Box,
  Camera,
  Circle,
  Clock,
  Container,
  Disc,
  DoorOpen,
  FileText,
  Flag,
  Flashlight,
  Frame,
  GitBranch,
  Grid: Grid3x3, // config name kept, lucide renamed the icon
  Lamp,
  Laptop,
  Lightbulb,
  Minus,
  // Config names with no lucide equivalent map to a sensible stand-in
  Mirror: Square,
  Hanger: Umbrella,
  LSquare: Square,
  TSquare: Square,
  USquare: Square,
  MonitorSpeaker,
  Move,
  Package,
  Palette,
  PenTool,
  RectangleHorizontal,
  RectangleVertical,
  Search,
  ShoppingCart,
  Sofa,
  Square,
  SquareDashedBottom,
  Sun,
  Table,
  Trees,
  Tv,
  Umbrella,
  User,
  Video,
  X,
  Zap,
  ChevronDown,
  ChevronRight,
};

export function getIconComponent(name?: string): LucideIcon | undefined {
  return name ? ICON_MAP[name] : undefined;
}
