import type { FurnitureItem } from '../types';

export interface LightingPreset {
  id: string;
  name: string;
  description: string;
  category: 'portrait' | 'product' | 'video' | 'general';
  lights: Omit<FurnitureItem, 'id'>[];
}

export const LIGHTING_PRESETS: LightingPreset[] = [
  // Portrait Lighting Presets
  {
    id: 'three-point-portrait',
    name: '3-Point Portrait',
    description: 'Classic setup with key, fill, and back light for professional portraits',
    category: 'portrait',
    lights: [
      {
        type: 'softbox-medium',
        name: 'Key Light',
        x: 3,
        y: 2,
        width: 2.5,
        height: 2.5,
        rotation: 0,
        color: '#FFD700',
        isLight: true,
        lightIntensity: 85,
        colorTemperature: 5600,
        beamAngle: 70,
        lightDirection: 135,
        zHeight: 7,
      },
      {
        type: 'softbox-small',
        name: 'Fill Light',
        x: 13,
        y: 3,
        width: 2,
        height: 2,
        rotation: 0,
        color: '#FFD700',
        isLight: true,
        lightIntensity: 40,
        colorTemperature: 5600,
        beamAngle: 85,
        lightDirection: 225,
        zHeight: 6,
      },
      {
        type: 'strobe-monolight',
        name: 'Back Light',
        x: 8,
        y: 12,
        width: 1.5,
        height: 1.5,
        rotation: 0,
        color: '#FFD700',
        isLight: true,
        lightIntensity: 60,
        colorTemperature: 5600,
        beamAngle: 45,
        lightDirection: 0,
        zHeight: 8,
      },
    ],
  },
  {
    id: 'rembrandt-lighting',
    name: 'Rembrandt Lighting',
    description: 'Dramatic portrait style with characteristic triangle of light on cheek',
    category: 'portrait',
    lights: [
      {
        type: 'softbox-large',
        name: 'Key Light (45°)',
        x: 2,
        y: 2,
        width: 3,
        height: 3,
        rotation: 0,
        color: '#FFD700',
        isLight: true,
        lightIntensity: 90,
        colorTemperature: 5200,
        beamAngle: 65,
        lightDirection: 135,
        zHeight: 7.5,
      },
      {
        type: 'reflector-white',
        name: 'Reflector (Fill)',
        x: 12,
        y: 4,
        width: 3,
        height: 4,
        rotation: 0,
        color: '#FFFFFF',
        isLight: false,
        zHeight: 0,
      },
    ],
  },
  {
    id: 'butterfly-lighting',
    name: 'Butterfly Lighting',
    description: 'Beauty/glamour lighting with light directly in front and above',
    category: 'portrait',
    lights: [
      {
        type: 'beauty-dish',
        name: 'Main Light',
        x: 8,
        y: 2,
        width: 2,
        height: 2,
        rotation: 0,
        color: '#FFD700',
        isLight: true,
        lightIntensity: 85,
        colorTemperature: 5600,
        beamAngle: 60,
        lightDirection: 180,
        zHeight: 8,
      },
      {
        type: 'reflector-white',
        name: 'Bottom Fill',
        x: 8,
        y: 8,
        width: 4,
        height: 2,
        rotation: 0,
        color: '#FFFFFF',
        isLight: false,
        zHeight: 0,
      },
    ],
  },
  {
    id: 'split-lighting',
    name: 'Split Lighting',
    description: 'Dramatic 50/50 split perfect for moody portraits',
    category: 'portrait',
    lights: [
      {
        type: 'strobe-monolight',
        name: 'Side Key',
        x: 1,
        y: 6,
        width: 1.5,
        height: 1.5,
        rotation: 0,
        color: '#FFD700',
        isLight: true,
        lightIntensity: 95,
        colorTemperature: 5400,
        beamAngle: 50,
        lightDirection: 90,
        zHeight: 7,
      },
    ],
  },

  // Product Photography Presets
  {
    id: 'product-high-key',
    name: 'High-Key Product',
    description: 'Bright, even lighting for clean product shots on white background',
    category: 'product',
    lights: [
      {
        type: 'softbox-large',
        name: 'Left Key',
        x: 2,
        y: 4,
        width: 3,
        height: 3,
        rotation: 0,
        color: '#FFD700',
        isLight: true,
        lightIntensity: 80,
        colorTemperature: 6000,
        beamAngle: 80,
        lightDirection: 90,
        zHeight: 7,
      },
      {
        type: 'softbox-large',
        name: 'Right Key',
        x: 13,
        y: 4,
        width: 3,
        height: 3,
        rotation: 0,
        color: '#FFD700',
        isLight: true,
        lightIntensity: 80,
        colorTemperature: 6000,
        beamAngle: 80,
        lightDirection: 270,
        zHeight: 7,
      },
      {
        type: 'led-panel-large',
        name: 'Top Light',
        x: 8,
        y: 2,
        width: 2,
        height: 2,
        rotation: 0,
        color: '#FFD700',
        isLight: true,
        lightIntensity: 60,
        colorTemperature: 6000,
        beamAngle: 90,
        lightDirection: 180,
        zHeight: 9,
      },
      {
        type: 'strobe-monolight',
        name: 'Background Light',
        x: 8,
        y: 14,
        width: 1.5,
        height: 1.5,
        rotation: 0,
        color: '#FFD700',
        isLight: true,
        lightIntensity: 100,
        colorTemperature: 6500,
        beamAngle: 100,
        lightDirection: 0,
        zHeight: 6,
      },
    ],
  },
  {
    id: 'product-dramatic',
    name: 'Dramatic Product',
    description: 'Single light setup for dramatic shadows and depth',
    category: 'product',
    lights: [
      {
        type: 'softbox-strip',
        name: 'Edge Light',
        x: 2,
        y: 4,
        width: 1,
        height: 4,
        rotation: 0,
        color: '#FFD700',
        isLight: true,
        lightIntensity: 90,
        colorTemperature: 5400,
        beamAngle: 55,
        lightDirection: 90,
        zHeight: 7,
      },
      {
        type: 'reflector-silver',
        name: 'Fill Reflector',
        x: 12,
        y: 5,
        width: 3,
        height: 4,
        rotation: 0,
        color: '#C0C0C0',
        isLight: false,
        zHeight: 0,
      },
    ],
  },

  // Video/Interview Presets
  {
    id: 'video-interview',
    name: 'Video Interview',
    description: 'Professional 2-light setup for interviews and talking heads',
    category: 'video',
    lights: [
      {
        type: 'led-panel-large',
        name: 'Key Light',
        x: 3,
        y: 3,
        width: 2,
        height: 2,
        rotation: 0,
        color: '#FFD700',
        isLight: true,
        lightIntensity: 75,
        colorTemperature: 5600,
        beamAngle: 75,
        lightDirection: 135,
        zHeight: 7,
      },
      {
        type: 'led-panel-medium',
        name: 'Fill Light',
        x: 11,
        y: 4,
        width: 1.5,
        height: 1.5,
        rotation: 0,
        color: '#FFD700',
        isLight: true,
        lightIntensity: 45,
        colorTemperature: 5600,
        beamAngle: 80,
        lightDirection: 225,
        zHeight: 6.5,
      },
    ],
  },
  {
    id: 'video-broadcast',
    name: 'Broadcast Setup',
    description: 'Full 4-light broadcast quality lighting for video production',
    category: 'video',
    lights: [
      {
        type: 'led-panel-large',
        name: 'Key Light',
        x: 3,
        y: 2,
        width: 2,
        height: 2,
        rotation: 0,
        color: '#FFD700',
        isLight: true,
        lightIntensity: 80,
        colorTemperature: 5600,
        beamAngle: 70,
        lightDirection: 135,
        zHeight: 7.5,
      },
      {
        type: 'led-panel-medium',
        name: 'Fill Light',
        x: 12,
        y: 3,
        width: 1.5,
        height: 1.5,
        rotation: 0,
        color: '#FFD700',
        isLight: true,
        lightIntensity: 50,
        colorTemperature: 5600,
        beamAngle: 80,
        lightDirection: 225,
        zHeight: 7,
      },
      {
        type: 'spotlight-fresnel',
        name: 'Back/Hair Light',
        x: 8,
        y: 12,
        width: 1.5,
        height: 1.5,
        rotation: 0,
        color: '#FFD700',
        isLight: true,
        lightIntensity: 65,
        colorTemperature: 5800,
        beamAngle: 40,
        lightDirection: 0,
        zHeight: 9,
      },
      {
        type: 'led-panel-small',
        name: 'Background Light',
        x: 8,
        y: 14,
        width: 1,
        height: 1,
        rotation: 0,
        color: '#FFD700',
        isLight: true,
        lightIntensity: 55,
        colorTemperature: 6000,
        beamAngle: 90,
        lightDirection: 0,
        zHeight: 6,
      },
    ],
  },

  // General Studio Presets
  {
    id: 'natural-window',
    name: 'Natural Window Light',
    description: 'Simulates soft window light with fill reflector',
    category: 'general',
    lights: [
      {
        type: 'softbox-large',
        name: 'Window Light',
        x: 1,
        y: 4,
        width: 3,
        height: 3,
        rotation: 0,
        color: '#FFD700',
        isLight: true,
        lightIntensity: 70,
        colorTemperature: 5800,
        beamAngle: 95,
        lightDirection: 90,
        zHeight: 7,
      },
      {
        type: 'reflector-white',
        name: 'Bounce Fill',
        x: 11,
        y: 5,
        width: 3,
        height: 4,
        rotation: 0,
        color: '#FFFFFF',
        isLight: false,
        zHeight: 0,
      },
    ],
  },
  {
    id: 'simple-single',
    name: 'Simple Single Light',
    description: 'Basic single softbox for beginners',
    category: 'general',
    lights: [
      {
        type: 'softbox-medium',
        name: 'Main Light',
        x: 4,
        y: 3,
        width: 2.5,
        height: 2.5,
        rotation: 0,
        color: '#FFD700',
        isLight: true,
        lightIntensity: 80,
        colorTemperature: 5600,
        beamAngle: 75,
        lightDirection: 120,
        zHeight: 7,
      },
    ],
  },
];

// Helper function to get presets by category
export const getPresetsByCategory = (category: LightingPreset['category']) => {
  return LIGHTING_PRESETS.filter(preset => preset.category === category);
};

// Helper function to get all categories
export const getPresetCategories = () => {
  return Array.from(new Set(LIGHTING_PRESETS.map(preset => preset.category)));
};
